export const Products = [
  {
    id: 1,
    name: "Flour - Fast / Rapid",
    description: "Pancreas injury NOS-open",
    price: 86.55,
    image: "https://placekitten.com/g/200/300",
    stock: 1,
  },
  {
    id: 2,
    name: "Sachet",
    description: "Fx lower humerus NOS-cl",
    price: 378.35,
    image: "https://placekitten.com/g/200/300",
    stock: 2,
  },
  {
    id: 3,
    name: "Banana - Leaves",
    description: "Mal neo stomach fundus",
    price: 102.28,
    image: "https://placekitten.com/g/200/300",
    stock: 3,
  },
  {
    id: 4,
    name: "Parsley - Fresh",
    description: "Thlasema Hb-S w/o crisis",
    price: 133.1,
    image: "https://placekitten.com/g/200/300",
    stock: 4,
  },
  {
    id: 5,
    name: "Muffin Batt - Blueberry Passion",
    description: "3rd burn w loss-elbow",
    price: 238.34,
    image: "https://placekitten.com/g/200/300",
    stock: 5,
  },
  {
    id: 6,
    name: "Fenngreek Seed",
    description: "Parox ventric tachycard",
    price: 371.45,
    image: "https://placekitten.com/g/200/300",
    stock: 6,
  },
  {
    id: 7,
    name: "Oil - Macadamia",
    description: "Autonomic nerve dis NEC",
    price: 367.46,
    image: "https://placekitten.com/g/200/300",
    stock: 7,
  },
  {
    id: 8,
    name: "Sauce - Fish 25 Ozf Bottle",
    description: "Late eff superficial inj",
    price: 312.55,
    image: "https://placekitten.com/g/200/300",
    stock: 8,
  },
  {
    id: 9,
    name: "Jicama",
    description: "Ot encph/mye ot inf else",
    price: 377.53,
    image: "https://placekitten.com/g/200/300",
    stock: 9,
  },
  {
    id: 10,
    name: "Flower - Commercial Bronze",
    description: "Postop shock,cardiogenic",
    price: 301.22,
    image: "https://placekitten.com/g/200/300",
    stock: 10,
  },
  {
    id: 11,
    name: "Puff Pastry - Slab",
    description: "Hantavirus infection",
    price: 386.64,
    image: "https://placekitten.com/g/200/300",
    stock: 11,
  },
  {
    id: 12,
    name: "Juice - Apple, 341 Ml",
    description: "3rd deg burn back",
    price: 336.77,
    image: "https://placekitten.com/g/200/300",
    stock: 12,
  },
  {
    id: 13,
    name: "Appetizer - Seafood Assortment",
    description: "Accident NEC",
    price: 118.26,
    image: "https://placekitten.com/g/200/300",
    stock: 13,
  },
  {
    id: 14,
    name: "Ice Cream - Vanilla",
    description: "Opn skul fx NEC-coma NOS",
    price: 378.72,
    image: "https://placekitten.com/g/200/300",
    stock: 14,
  },
  {
    id: 15,
    name: "Muffin Batt - Ban Dream Zero",
    description: "BMI 32.0-32.9,adult",
    price: 147.43,
    image: "https://placekitten.com/g/200/300",
    stock: 15,
  },
  {
    id: 16,
    name: "Sprite - 355 Ml",
    description: "Acc d/t avalanche",
    price: 362.18,
    image: "https://placekitten.com/g/200/300",
    stock: 16,
  },
  {
    id: 17,
    name: "Octopus - Baby, Cleaned",
    description: "Hem early pg NEC-antepar",
    price: 285.81,
    image: "https://placekitten.com/g/200/300",
    stock: 17,
  },
  {
    id: 18,
    name: "Cookies Oatmeal Raisin",
    description: "Sprain ulnar collat lig",
    price: 106.64,
    image: "https://placekitten.com/g/200/300",
    stock: 18,
  },
  {
    id: 19,
    name: "Pail For Lid 1537",
    description: "Sprain hip & thigh NOS",
    price: 322.42,
    image: "https://placekitten.com/g/200/300",
    stock: 19,
  },
  {
    id: 20,
    name: "Tea - Orange Pekoe",
    description: "Opn skl/oth fx-prol coma",
    price: 198.83,
    image: "https://placekitten.com/g/200/300",
    stock: 20,
  },
  {
    id: 21,
    name: "Wine - White, Pelee Island",
    description: "Disloc vertebra NOS-open",
    price: 192.45,
    image: "https://placekitten.com/g/200/300",
    stock: 21,
  },
  {
    id: 22,
    name: "Nectarines",
    description: "Sexual sadism",
    price: 199.46,
    image: "https://placekitten.com/g/200/300",
    stock: 22,
  },
  {
    id: 23,
    name: "Muffin Mix - Oatmeal",
    description: "Lte ef-mplga low lmb NOS",
    price: 149.56,
    image: "https://placekitten.com/g/200/300",
    stock: 23,
  },
  {
    id: 24,
    name: "Turnip - White, Organic",
    description: "Spin bif w hydrceph-dors",
    price: 293.17,
    image: "https://placekitten.com/g/200/300",
    stock: 24,
  },
  {
    id: 25,
    name: "Mustard Prepared",
    description: "Fx mid/prx phal, hand-cl",
    price: 91.04,
    image: "https://placekitten.com/g/200/300",
    stock: 25,
  },
];



export const PromiseProducts = new Promise((resolve, reject) => {
  let condition = true;
  if (condition) {
    setTimeout(() => {
      resolve(Products);
    }, 2000);
  } else {
    reject(console.log("Error"));
  }
});

